---
title: "Reaction Time Graphs"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

d <- read.csv("../data/processed.csv")
```

# Looking at overall Log RT for the data

Before removing outliers

## Summary Stats
```{r}

ggplot(d, aes(RT, fill=Task)) +
  geom_density(alpha = .5)

summary(d$RT)
```

Long tail justifies outlier removal?
```{r}
ggplot(d, aes(LogRT, fill=Task)) +
  geom_density(alpha = .5)

summary(d$LogRT)
```

# RT by Accuracy

```{r}
agr = d %>%
    group_by(Task,LogRT) %>%
    summarize(MeanAccuracy = mean(Accuracy) )


ggplot(agr, aes(x = MeanAccuracy, y = LogRT, fill = MeanAccuracy)) +
  geom_boxplot(alpha = 0.7) + # Boxplot
  geom_jitter(position = position_jitter(0.2), color = "black", size = 1.5, alpha = 0.5) + # Add jittered points
  facet_wrap(~Task) +
  labs(title = "Reaction Time by Accuracy",
       x = "Accuracy",
       y = "Reaction Time (ms)") +
  theme_minimal() +
  theme(legend.position = "none") # Remove legend

```

```{r}
ggplot(d, aes(x = Accuracy, y = LogRT, fill = Task)) +
  geom_violin(alpha = 0.7) + # Violin plot
  geom_jitter(position = position_jitter(0.2), color = "black", size = 1.5, alpha = 0.5) + # Add jittered points
  labs(title = "Reaction Time by Accuracy",
       x = "Accuracy",
       y = "Reaction Time (ms)")
  # theme_minimal() +
  # theme(legend.position = "none") # Remove legend
```




# LogRT by Task

```{r}

agr = d %>%
    group_by(Task,Word) %>%
    summarize(MeanLogRT = mean(LogRT), 
              CILow = ci.low(LogRT), 
              CIHigh = ci.high(LogRT)) %>%
    mutate(YMin = MeanLogRT - CILow, 
           YMax = MeanLogRT + CIHigh)

ggplot(agr, aes(x=MeanLogRT, fill=Task)) +
  geom_density(alpha = .4)

ggplot(agr, aes(x=Task, y=MeanLogRT,fill=Task)) + 
    geom_violin(trim=FALSE,alpha=.4) +
    geom_jitter(shape=16, position=position_jitter(0.2)) +
    # geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position="dodge", show.legend = FALSE) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = "none")

```

# RT by Task
```{r}

agr = d %>%
    group_by(Task,Word) %>%
    summarize(MeanRT = mean(RT), 
              CILow = ci.low(RT), 
              CIHigh = ci.high(RT)) %>%
    mutate(YMin = MeanRT - CILow, 
           YMax = MeanRT + CIHigh)

ggplot(agr, aes(x=MeanRT, fill=Task)) +
  geom_density(alpha = .4)

ggplot(agr, aes(x=Task, y=MeanRT,fill=Task)) + 
    geom_violin(trim=FALSE,alpha=.4) +
    geom_jitter(shape=16, position=position_jitter(0.2)) +
    # geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position="dodge", show.legend = FALSE) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = "none")

```

# LogRT by BlockOrder and Task
```{r}

agr = d %>%
    group_by(BlockOrder,Task,Word) %>%
    summarize(MeanLogRT = mean(LogRT), 
              CILow = ci.low(LogRT), 
              CIHigh = ci.high(LogRT)) %>%
    mutate(YMin = MeanLogRT - CILow, 
           YMax = MeanLogRT + CIHigh)

ggplot(agr, aes(x=MeanLogRT, fill=Task)) +
  geom_density(alpha = .4)

ggplot(agr, aes(x=MeanLogRT, fill=Task)) +
  facet_wrap(~BlockOrder) +
  geom_density(alpha = .4)

ggplot(agr, aes(x=Task, y=MeanLogRT,fill=BlockOrder)) + 
    geom_violin(trim=FALSE,alpha=.4) +
    geom_jitter(shape=16, position=position_jitter(0.2))

```

# RT by BlockOrder and Task
```{r}

agr = d %>%
    group_by(BlockOrder,Task,Word) %>%
    summarize(MeanRT = mean(RT), 
              CILow = ci.low(RT), 
              CIHigh = ci.high(RT)) %>%
    mutate(YMin = MeanRT - CILow, 
           YMax = MeanRT + CIHigh)

ggplot(agr, aes(x=MeanRT, fill=Task)) +
  geom_density(alpha = .4)

ggplot(agr, aes(x=MeanRT, fill=Task)) +
  facet_wrap(~BlockOrder) +
  geom_density(alpha = .4)

ggplot(agr, aes(x=Task, y=MeanRT,fill=BlockOrder)) + 
    geom_violin(trim=FALSE,alpha=.4) +
    geom_jitter(shape=16, position=position_jitter(0.2))

```


# By Item

```{r,fig.width=10, fig.height=5}
agr = d %>%
    group_by(Task,Word) %>%
    summarize(MeanRT = mean(RT), CILow = ci.low(RT), CIHigh = ci.high(RT)) %>%
    mutate(YMin = MeanRT - CILow, YMax = MeanRT + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Word,y=MeanRT,fill=Task)) +
  geom_bar(position=dodge,stat="identity") +
  # facet_wrap(~Task) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```

```{r,fig.width=10, fig.height=15}
agr = d %>%
    group_by(BlockOrder,Task,Word) %>%
    summarize(MeanRT = mean(RT), CILow = ci.low(RT), CIHigh = ci.high(RT)) %>%
    mutate(YMin = MeanRT - CILow, YMax = MeanRT + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanRT,fill=BlockOrder)) +
  geom_bar(position=dodge,stat="identity") +
  facet_wrap(~Word) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```


## By ConcValCombo category and Task

### Mean Raw RT and Effects of Word Valence/Concreteness

```{r}

agr = d %>%
    group_by(Task,ConcValCombo) %>%
    reframe(MeanRT = mean(RT), CILow = ci.low(RT), CIHigh = ci.high(RT)) %>%
    mutate(YMin = MeanRT - CILow, YMax = MeanRT + CIHigh)


dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanRT,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  # facet_wrap(~Task) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")


```

### Mean Raw RT and Effects of Word Valence/Concreteness

```{r}

agr = d %>%
    group_by(BlockOrder,Task,ConcValCombo) %>%
    reframe(MeanRT = mean(RT), CILow = ci.low(RT), CIHigh = ci.high(RT)) %>%
    mutate(YMin = MeanRT - CILow, YMax = MeanRT + CIHigh)


dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanRT,fill=BlockOrder)) +
  geom_bar(position=dodge,stat="identity") +
  facet_wrap(~ConcValCombo) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")


```
