---
title: "Pilot 5: playing around with trial order"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---



```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../../helpers.R")

d <- read.csv("../data/processed.csv")
```

```{r}
# Assuming `df` is your data frame with columns `ID.true` and `Word`
d <- d %>%
  group_by(Task,ID.true,Word) %>%                # Group by `ID.true` and `Word`
  mutate(WordOrder = row_number()) %>%       # Create the `WordOrder` column with the order of each word's appearance
  ungroup()     # Ungroup to finish

```

```{r}
table(d$WordOrder)
```


```{r}
ggplot(d, aes(LogReactionTime, fill=Task)) +
  geom_density(alpha = .5) +
  facet_wrap(~WordOrder)
```

```{r,fig.width=10, fig.height=10}
agr <- d %>%
  group_by(Task,WordOrder) %>% 
  mutate(MeanRT = mean(ReactionTime), 
          CILow = ci.low(ReactionTime), 
          CIHigh = ci.high(ReactionTime)) %>%
  mutate(YMin = MeanRT - CILow, 
         YMax = MeanRT + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=WordOrder,y=MeanRT,fill=Task)) +
  geom_bar(position=dodge,stat="identity") +
  # facet_wrap(~Word) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))
  # guides(fill = "none")

```

```{r}
d <- d %>% 
  filter(Accuracy == 1)
```


```{r}
ggplot(d, aes(LogReactionTime, fill=Task)) +
  geom_density(alpha = .5) +
  facet_wrap(~WordOrder)
```

```{r,fig.width=10, fig.height=10}
agr <- d %>%
  group_by(Task,WordOrder) %>% 
  mutate(MeanRT = mean(ReactionTime), 
          CILow = ci.low(ReactionTime), 
          CIHigh = ci.high(ReactionTime)) %>%
  mutate(YMin = MeanRT - CILow, 
         YMax = MeanRT + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=WordOrder,y=MeanRT,fill=Task)) +
  geom_bar(position=dodge,stat="identity") +
  # facet_wrap(~Word) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))
  # guides(fill = "none")

```


