---
title: "Cluster Analysis"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
library(ggrepel)
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

# v1 <- read_csv("../../01_verbs/exploratory_all_data/data/processed.csv")
# v1["Category"] <- "Verbs"

v <- read_csv("../../01_concreteness/01_verbs/data/processed.csv")
v["Category"] <- "Verbs"
v["Experiment"] <- "Ex1: Conc-Abs"

n <- read_csv("../../01_concreteness/02_nouns/data/processed.csv")
n["Category"] <- "Nouns"
n["Experiment"] <- "Ex1: Conc-Abs"

a <- read_csv("../../01_concreteness/03_adjectives/data/processed.csv")
a["Category"] <- "Adjs"
a["Experiment"] <- "Ex1: Conc-Abs"

a2 <- read_csv("../../06_soc-phys/00_pilot/data/processed.csv")
a2["Category"] <- "Adjs"
a2["Experiment"] <- "Ex2b: Phys-Soc"

v2 <- read_csv("../../02_phys-psych/01_experiment/data/processed.csv")
v2["Category"] <- "Verbs"
v2["Experiment"] <- "Ex2a: Phys-Psych"


n2 <- read_csv("../../04_animacy/data/processed.csv")
n2["Category"] <- "Nouns"
n2["Experiment"] <- "Ex3: Animacy"

s <- read_csv("../../05_syntactic/01_experiment/data/processed.csv")
s["Experiment"] <- "Ex4: Syntactic"



d <- bind_rows(v,n,a,a2,v2,n2,s)

```

```{r}
table(d$Task)
```

