---
title: "Pilot 4: Switch Cost"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

d <- read.csv("../data/corrected.csv")
```

# First make the pairs, then remove non-accurate trials
otherwise, might not be getting the right order
```{r}
d <- d %>%
  # filter(AccuracyCorrected == 1) %>% 
  mutate(UniqueTrial = paste(ID.true,Task,sep="-")) %>% 
  separate(
    ConcValFinal,            # Column to split
    into = c("ConcreteValue", "ValenceValue"),  # New column names
    sep = "-"                # Separator to split at
  )
```


```{r}
# Process the data
# Process the data
output <- d %>%
  group_by(UniqueTrial) %>%
  mutate(
    # Create WordPair using Word column values of consecutive rows
    WordPair = paste0(Word, "-", lead(Word)),
    # Determine SwitchCostVal by comparing ValenceValue with the next row
    SwitchCostVal = case_when(
      ValenceValue == lead(ValenceValue) ~ "NoSwitch",
      ValenceValue != lead(ValenceValue) ~ "Switch",
      TRUE ~ NA_character_  # Handle edge cases
    ),
    # Determine SwitchCostConc by comparing ConcreteValue with the next row
    SwitchCostConc = case_when(
      ConcreteValue == lead(ConcreteValue) ~ "NoSwitch",
      ConcreteValue != lead(ConcreteValue) ~ "Switch",
      TRUE ~ NA_character_  # Handle edge cases
    ),
    # FirstWordRT is the ReactionTime of the current row
    FirstWordLogRT = LogReactionTime,
    # SecondWordRT is the ReactionTime of the next row
    SecondWordLogRT = lead(LogReactionTime),
    # FirstWordRT is the ReactionTime of the current row
    FirstWordRT = ReactionTime,
    # SecondWordRT is the ReactionTime of the next row
    SecondWordRT = lead(ReactionTime),
    # FirstWordRT is the ReactionTime of the current row
    FirstWordAccuracy = AccuracyCorrected,
    # SecondWordRT is the ReactionTime of the next row
    SecondWordAccuracy = lead(AccuracyCorrected),
    # create the combo column
    SwitchCombo = paste(SwitchCostConc,SwitchCostVal,sep='-'),
    RT_Difference = SecondWordLogRT - FirstWordLogRT                     # Calculate the difference between RTs
  ) %>%
  # Remove rows without valid pairings (e.g., last row in each UniqueTrial group)
  filter(!is.na(lead(Word))) %>%
  ungroup() 
# %>%
  # select(UniqueTrial, ConcreteValue, ValenceValue, WordPair, SwitchCostVal, SwitchCostConc)


# Print the resulting dataframe
table(output$SwitchCostVal)

table(output$SwitchCostConc)

table(output$SwitchCostConc,output$SwitchCostVal)

table(output$FirstWordAccuracy,output$SecondWordAccuracy)

```

# Filter out inaccurate trials
```{r}
output_acc <- output %>% 
  filter((FirstWordAccuracy == 1) & (SecondWordAccuracy == 1))

nrow(output_acc)/nrow(output)*100

```


```{r}

agr <- output_acc %>% 
  group_by(WordPair,SwitchCombo) %>% 
  mutate(MeanSecondWordLogRT = mean(SecondWordLogRT))

ggplot(output_acc, aes(SecondWordLogRT, fill=SwitchCombo)) +
  geom_density(alpha = .5)


agr <- output %>% 
  group_by(WordPair,Task,SwitchCombo) %>% 
  summarize(MeanSecondWordLogRT = mean(SecondWordLogRT))

ggplot(agr, aes(MeanSecondWordLogRT, fill=SwitchCombo)) +
  geom_density(alpha = .5) +
  facet_wrap(~Task)
  
```

# Plot the difference between First and Second Word RT as a function of SwitchCombo
```{r}
# Plot the RT difference as a function of SwitchCombo
ggplot(agr, aes(x = SwitchCombo, y = SecondWordLogRT)) +
  geom_boxplot(fill = "lightblue", color = "darkblue", outlier.color = "red") +
  geom_jitter(width = 0.2, alpha = 0.6) +
  labs(
    title = "RT Difference by Switch Combo",
    x = "Switch Combo (Valence-Concreteness)",
    y = "RT Difference (ms)"
  )
  # theme_minimal() +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))


# Plot the RT difference as a function of SwitchCombo using a violin plot
ggplot(output_acc, aes(x = SwitchCombo, y = SecondWordRT, fill=Task)) +
  geom_violin(fill = "lightblue", color = "darkblue", trim = FALSE) +
  geom_jitter(width = 0.2, alpha = 0.6) +
  labs(
    title = "RT Difference by Switch Combo",
    x = "Switch Combo (Valence-Concreteness)",
    y = "Log RT for second word"
  )
```


# Remove outliers

```{r}
# Remove subjects with ReactionTime higher than 3x IQR
summary(output_acc$SecondWordLogRT)
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 4.575   6.426   6.594   6.679   6.841  11.417 
range(output_acc$SecondWordLogRT)

hist(output_acc$SecondWordLogRT, breaks=100, col="lightblue", xlab="SecondWordLogRT (ms)",
        main="Histogram with Normal Curve")

quantile(output_acc$SecondWordLogRT)
IQR(output_acc$SecondWordLogRT)*3 # 0.7526289
cutoff.high <- quantile(output_acc$SecondWordLogRT)[4] + IQR(output_acc$SecondWordLogRT)*3 # 8.419261
cutoff.low <- quantile(output_acc$SecondWordLogRT)[2] - IQR(output_acc$SecondWordLogRT)*3# 6.5088838.419261


# remove subjects with ReactionTime higher than 3 x IQR
df.outliers.removed <- subset(output_acc, (output_acc$SecondWordLogRT > cutoff.low) & (output_acc$SecondWordLogRT < cutoff.high))

hist(df.outliers.removed$SecondWordLogRT, col="lightblue", xlab="SecondWordLogRT (ms)",
        main="Histogram with Normal Curve")


```


```{r}
ggplot(df.outliers.removed, aes(x=SecondWordLogRT, fill=SwitchCombo)) +
  facet_wrap(~Task) +
  geom_density(alpha = .4)

ggplot(df.outliers.removed, aes(x=SecondWordLogRT, fill=Task)) +
  facet_wrap(~SwitchCombo) +
  geom_density(alpha = .4)


```


```{r}
agr <- df.outliers.removed %>% 
  group_by(WordPair,Task,SwitchCombo) %>% 
  summarize(MeanSecondWordLogRT = mean(SecondWordLogRT))

ggplot(agr, aes(MeanSecondWordLogRT, fill=SwitchCombo)) +
  geom_density(alpha = .5) +
  facet_wrap(~Task)
  
```

# Plot the difference between First and Second Word RT as a function of SwitchCombo
```{r}
# Plot the RT difference as a function of SwitchCombo
ggplot(agr, aes(x = SwitchCombo, y = SecondWordLogRT)) +
  geom_boxplot(fill = "lightblue", color = "darkblue", outlier.color = "red") +
  geom_jitter(width = 0.2, alpha = 0.6) +
  facet_wrap(~Task) +
  labs(
    title = "RT Difference by Switch Combo",
    x = "Switch Combo (Valence-Concreteness)",
    y = "RT Difference (ms)"
  )
  # theme_minimal() +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))


# Plot the RT difference as a function of SwitchCombo using a violin plot
ggplot(df.outliers.removed, aes(x = Task, y = SecondWordLogRT)) +
  geom_violin(fill = "lightblue", color = "darkblue", trim = FALSE) +
  # geom_jitter(width = 0.2, alpha = 0.6) +
  facet_wrap(~SwitchCombo) +
  labs(
    title = "RT Difference by Switch Combo",
    x = "Switch Combo (Valence-Concreteness)",
    y = "Log RT for second word"
  )
```


```{r, include=FALSE, warning=FALSE, echo=FALSE}
df.outliers.removed$Task <- as.factor(df.outliers.removed$Task)
df.outliers.removed$SwitchCombo <- as.factor(df.outliers.removed$SwitchCombo)

contrasts(output_acc$SwitchCombo)
contrasts(as.factor(output_acc$Task))

center = df.outliers.removed %>%
  mutate(cTask = as.numeric(Task)-mean(as.numeric(Task)),
         # cAccuracyCorrected = as.numeric(AccuracyCorrected)-mean(as.numeric(AccuracyCorrected)),
         # cBlockOrder = as.numeric(BlockOrder)-mean(as.numeric(BlockOrder))
         )
  
  # droplevels()

```


```{r}

m = lmer(SecondWordLogRT ~ cTask*SwitchCombo + (1|UniqueTrial), data=center)
summary(m)
```





