---
title: "playing around with trial order"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---



```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

d <- read.csv("../data/best_words.csv")
```

```{r}
# Assuming `df` is your data frame with columns `ID.true` and `Word`
df <- df %>%
  group_by(ID.true, Word) %>%                # Group by `ID.true` and `Word`
  mutate(WordOrder = row_number()) %>%       # Create the `WordOrder` column with the order of each word's appearance
  ungroup()                                  # Ungroup to finish
```

