---
title: "Power Analysis"
author: "author"
date: "`r Sys.Date()`"
output: html_document
---
  
```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(simr)
library(pwr)
library(MASS)  # For generating random data
library(lme4)

cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
# source("../../helpers.R")
d <- read.csv("../01_concreteness/00_pilot/01_verbs/05_pilot/data/processed.csv")
```

# Fit the model

```{r}

# Fit your model
fit <- lmer(LogReactionTime ~ Task + 
            (1+Task|Word) + 
            (1+Task|ID.true) + 
              # random slope for the repeated measure factor 
              # and interaction term to represent the repetition
            (1+Task|ID.true:Word), 
            data = d)

summary(fit)
# Run power analysis
# 1. Modify the model to specify the desired sample size
extended_fit <- extend(fit, along = "ID.true", n = 40)  # Replace "ID.true" with your grouping variable

# 2. Run the power analysis on the extended model
power <- powerSim(extended_fit, nsim = 200)
print(power)

```


# Extend

```{r}
# Simplify random effects:
fit_simple <- lmer(LogReactionTime ~ Task + 
                   (1 | Word) +          # Remove Task slope for Word
                   (1 + Task || ID.true) +   # Uncorrelated slopes/intercepts
                   (1 | ID.true:Word),   # Remove Task slope for interaction
                 data = d)


extended_fit <- extend(fit_simple, along = "ID.true", n = 20)  # Replace "ID.true" with your grouping variable

# 2. Run the power analysis on the extended model
power <- powerSim(extended_fit, nsim = 200)
print(power)
```


## Run a power curve
```{r}
fit <- lmer(LogReactionTime ~ Task + 
            (1+Task|Word) + 
            (1+Task|ID.true), 
            # (1+Task|ID.true:Word), 
            data = d)

# Run the power curve
power_curve <- powerCurve(fit_simple, along = "ID.true", breaks = seq(20, 80, by = 10), nsim = 200)

# Plot the power curve
plot(power_curve)

summary(power_curve)
isSingular(fit_simple, tol = 1e-4)

```


```{r}
# library(brms)
# brm_model <- brm(LogReactionTime ~ Task + (1 + Task | Word) + (1 + Task | ID.true), 
#                  data = d, prior = set_prior("normal(0,1)", class = "sd"))

```

