---
title: "Stimuli"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
library(ggrepel)
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../helpers.R")

v2 <- read_csv("../02_phys-psych/data/processed.csv")
v2["Category"] <- "Verbs"

v1 <- read_csv("../01_concreteness/01_verbs/data/processed.csv")
v["Category"] <- "Verbs"

# n1 <- read_csv("../../02_nouns/01_pilot/data/processed.csv")
# n1["Category"] <- "Nouns"

n1 <- read_csv("../01_concreteness/02_nouns/data/processed.csv")
n1["Category"] <- "Nouns"

n2 <- read_csv("../01_animacy/data/processed.csv")
n2["Category"] <- "Nouns"

# n3 <- read_csv("../../02_nouns/03_pilot/data/processed.csv")
# n3["Category"] <- "Nouns"

a1 <- read_csv("../01_concreteness/03_adjectives/data/processed.csv")
a1["Category"] <- "Adjs"

a2 <- read_csv("../00_pilot/04_soc-phys/data/processed.csv")
a2["Category"] <- "Adjs"
# 
s <- read_csv("../05_syntactic/01_experiment/data/processed.csv")


d <- bind_rows(v,n2,a1)

# table(d$WhoseList)
```

# Concrete - verbs

```{r}
highest %>%
  group_by(ConcValCombo) %>%
  summarise(Word_List = paste(Word, collapse = ", ")) %>%
  pivot_wider(names_from = ConcValCombo, values_from = Word_List) %>%
  knitr::kable() %>% 
  kable_styling(full_width = TRUE, position = "center", bootstrap_options = c("striped", "hover"))
```

