---
title: "Analysis of Arousal"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
library(ggrepel)
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

# v1 <- read_csv("../../01_verbs/exploratory_all_data/data/processed.csv")
# v1["Category"] <- "Verbs"

v <- read_csv("../../01_concreteness/01_verbs/data/processed.csv")
v["Category"] <- "Verbs"
v["Experiment"] <- "Ex1a: Conc-Abs (Verbs)"

n <- read_csv("../../01_concreteness/02_nouns/data/processed.csv")
n["Category"] <- "Nouns"
n["Experiment"] <- "Ex1b: Conc-Abs (Nouns)"

a <- read_csv("../../01_concreteness/03_adjectives/data/processed.csv")
a["Category"] <- "Adjs"
a["Experiment"] <- "Ex1c: Conc-Abs (Adjs)"

a2 <- read_csv("../../03_phys-soc/00_pilot/02_pilot/data/processed.csv")
a2["Category"] <- "Adjs"
a2["Experiment"] <- "Ex2b: Phys-Soc (Adjs)"

v2 <- read_csv("../../02_phys-psych/01_experiment/data/processed.csv")
v2["Category"] <- "Verbs"
v2["Experiment"] <- "Ex2a: Phys-Psych (Verbs)"


n2 <- read_csv("../../04_animacy/01_experiment/data/processed.csv")
n2["Category"] <- "Nouns"
n2["Experiment"] <- "Ex3: Animacy (Nouns)"

s <- read_csv("../../05_syntactic/01_experiment/data/processed.csv")
s["Experiment"] <- "Ex4: Syntactic (N v. V)"

arousal <- read_csv("../data/total_words_measures.csv")
nrow(arousal)
d <- bind_rows(v,n,a,a2,v2,n2,s)
nrow(d)
dt <- merge(d,arousal, by=c("Word","Experiment"))
nrow(dt)

```

## For some reason there are sopme missing words, need to figure out why this is since Warriner et al was the starting point so they should be there.

```{r}

# Figure out what 
df <- anti_join(d,dt)
print(unique(df$Word))

nrow(df)
```

# Nested Model Comparison


## Remove outliers

```{r}
# First remove inaccurate participants
length(unique(d$ID.true))
inacc.parts <- dt %>% 
  group_by(Experiment,ID.true,Task,Category) %>% 
  summarise(MeanAccuracy = mean(Accuracy)) %>% 
  filter(MeanAccuracy < .75)
# How many participants have Accuracy < .75?
length(unique(inacc.parts$ID.true))
# Remove them
d.inaccurate.removed <- dt %>% 
  anti_join(inacc.parts, by = "ID.true")
# Sanity check
length(unique(d.inaccurate.removed$ID.true))


# Second, remove all inaccurate trials
orig <- nrow(d.inaccurate.removed)
d.inaccurate.removed <- d.inaccurate.removed %>% 
  filter(Accuracy == 1)
nrow(d.inaccurate.removed)/orig*100


# Third, Remove subjects with ReactionTime higher than 3x IQR
summary(d.inaccurate.removed$LogReactionTime)
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 6.924   7.328   7.436   7.479   7.579  10.008 
range(d.inaccurate.removed$LogReactionTime)

hist(d.inaccurate.removed$LogReactionTime, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)
IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 0.7526289
cutoff.high <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[4] + IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 8.419261
cutoff.low <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[2] - IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3# 6.5088838.419261


# remove subjects with ReactionTime higher than 3 x IQR
df.outliers.removed <- subset(d.inaccurate.removed, (d.inaccurate.removed$LogReactionTime > cutoff.low) & (d.inaccurate.removed$LogReactionTime < cutoff.high))

hist(df.outliers.removed$LogReactionTime, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

```

```{r}

str(df.outliers.removed)
dcen <- df.outliers.removed %>% 
  mutate(
         Task = ifelse(Task == "Valence", "Valence", "Conceptual"),
         Task = factor(Task, levels = c("Conceptual","Valence")),
         cTask = as.numeric(Task)-mean(as.numeric(Task)),
         Word = as.factor(Word),
         ID.true = as.factor(ID.true),
         Experiment = as.factor(Experiment)
         )

m <- lmer(LogReactionTime ~ cTask*Experiment*A.Mean.Sum + (1+cTask|Word) + (1+cTask|ID.true), data = dcen)
summary(m)

m.s <- lmer(LogReactionTime ~ cTask*Experiment + (1+cTask|Word) + (1+cTask|ID.true), data = dcen)


anova(m,m.s, test="chisq")

```

