---
title: "Everything Graphs: Categorization Task"
author: "author"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
library(ggrepel)
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

# v1 <- read_csv("../../01_verbs/exploratory_all_data/data/processed.csv")
# v1["Category"] <- "Verbs"

v <- read_csv("../../01_concreteness/01_verbs/data/processed.csv")
v["Category"] <- "Verbs"
v["Experiment"] <- "Ex1a: Conc-Abs (Verbs)"
v["TruthCond"] <- "Conc-Abs"

n <- read_csv("../../01_concreteness/02_nouns/data/processed.csv")
n["Category"] <- "Nouns"
n["Experiment"] <- "Ex1b: Conc-Abs (Nouns)"
v["TruthCond"] <- "Conc-Abs"

a <- read_csv("../../01_concreteness/03_adjectives/data/processed.csv")
a["Category"] <- "Adjs"
a["Experiment"] <- "Ex1c: Conc-Abs (Adjs)"
a["TruthCond"] <- "Conc-Abs"

a2 <- read_csv("../../03_phys-soc/01_experiment/data/processed.csv")
a2["Category"] <- "Adjs"
a2["Experiment"] <- "Ex2b: Phys-Soc (Adjs)"
a2["TruthCond"] <- "Phys-Soc/Psych"

v2 <- read_csv("../../02_phys-psych/01_experiment/data/processed.csv")
v2["Category"] <- "Verbs"
v2["Experiment"] <- "Ex2a: Phys-Psych (Verbs)"
v2["TruthCond"] <- "Phys-Soc/Psych"


n2 <- read_csv("../../04_animacy/01_experiment/data/processed.csv")
n2["Category"] <- "Nouns"
n2["Experiment"] <- "Ex3: Animacy (Nouns)"
n2["TruthCond"] <- "Animacy"

s <- read_csv("../../05_syntactic/01_experiment/data/processed.csv")
s["Experiment"] <- "Ex4: Syntactic (N v. V)"
s["TruthCond"] <- "Syntactic"


d <- bind_rows(v,n,a,a2,v2,n2,s)
names(d)

length(unique(a2$ID.true))



# words <- unique(d[,c("Word","Experiment")])
# write.csv(words,"../data/total_words.csv")

```

# Reaction Time

## Remove outliers

```{r}
# First remove inaccurate participants
length(unique(d$ID.true))
inacc.parts <- d %>% 
  group_by(Experiment,ID.true,Task,Category) %>% 
  summarise(MeanAccuracy = mean(Accuracy)) %>% 
  filter(MeanAccuracy < .75)
# How many participants have Accuracy < .75?
length(unique(inacc.parts$ID.true))
# Remove them
d.inaccurate.removed <- d %>% 
  anti_join(inacc.parts, by = "ID.true")
# Sanity check
length(unique(d.inaccurate.removed$ID.true))


# Second, remove all inaccurate trials
orig <- nrow(d.inaccurate.removed)
d.inaccurate.removed <- d.inaccurate.removed %>% 
  filter(Accuracy == 1)
nrow(d.inaccurate.removed)/orig*100


# Third, Remove subjects with ReactionTime higher than 3x IQR
summary(d.inaccurate.removed$LogReactionTime)
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 6.924   7.328   7.436   7.479   7.579  10.008 
range(d.inaccurate.removed$LogReactionTime)

hist(d.inaccurate.removed$LogReactionTime, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)
IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 0.7526289
cutoff.high <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[4] + IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 8.419261
cutoff.low <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[2] - IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3# 6.5088838.419261


# remove subjects with ReactionTime higher than 3 x IQR
df.outliers.removed <- subset(d.inaccurate.removed, (d.inaccurate.removed$LogReactionTime > cutoff.low) & (d.inaccurate.removed$LogReactionTime < cutoff.high))

hist(df.outliers.removed$LogReactionTime, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

# write_csv(df.outliers.removed,"../data/categorization.csv")
nrow(df.outliers.removed)

length(unique(d$ID.true)) - length(unique(df.outliers.removed$ID.true))

# What percentage of data lost?
(1 - nrow(df.outliers.removed)/nrow(d)) *100

```


```{r}
agr <- df.outliers.removed %>% 
  group_by(Experiment,Task) %>% 
    summarize(MeanReactionTime = mean(ReactionTime), 
              CILow = ci.low(ReactionTime), 
              CIHigh = ci.high(ReactionTime)) %>%
    mutate(YMin = MeanReactionTime - CILow, 
           YMax = MeanReactionTime + CIHigh)
nrow(agr)
print(agr)
# write.csv(agr,"../data/categorization_agg.csv")
```



## Summary Stats
```{r}
agr <- df.outliers.removed %>% 
  group_by(Experiment,Task) %>% 
  summarize(MeanRT = mean(ReactionTime),
            SD = sd(ReactionTime),
            MeanLogRT = mean(LogReactionTime))
```

# Total RT with median and mode stats

## horizontal format
```{r}
agr <- df.outliers.removed %>%
    group_by(Experiment,Task,Word) %>%
    summarize(MeanReactionTime = mean(ReactionTime), 
              CILow = ci.low(ReactionTime), 
              CIHigh = ci.high(ReactionTime)) %>%
    mutate(YMin = MeanReactionTime - CILow, 
           YMax = MeanReactionTime + CIHigh)

agr$Task <- ifelse(agr$Task == "Valence", "Valence", "TruthCond")
agr$Task <- factor(agr$Task, levels = c("TruthCond","Valence"))

# Set dodge width to match violin grouping
dodge_width <- 0.9

ggplot(agr, aes(x = Experiment, y = MeanReactionTime, fill = Task)) + 
  geom_violin(trim = FALSE, alpha = 0.4, position = position_dodge(width = dodge_width)) +

  # Add mean point with matching dodge
  stat_summary(fun = mean,
               geom = "point",
               shape = 23,
               size = 2,
               position = position_dodge(width = dodge_width)) +
  
  stat_summary(fun = median,
                geom = "crossbar",
                width = 0.3, 
                linewidth = 0.2,
                position = position_dodge(width = dodge_width)) +
  
  labs(y = "Mean Reaction Time", x = "Experiment") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    axis.title.x=element_blank(),
    text = element_text(family = "Helvetica"),
    axis.title.y = element_text(size = 16),     # x-axis title
    axis.text.y  = element_text(size = 12),     # y-axis ticks
    axis.text.x  = element_text(size = 12),     # x-axis ticks
  )



ggsave("../graphs/total_rt_paper2.jpg",width = 8, height = 4)
ggsave("../graphs/exp1_paper.pdf",width = 8, height = 4)
```



## vertical format
```{r}
agr <- df.outliers.removed %>%
    group_by(Experiment,Task,Word) %>%
    summarize(MeanReactionTime = mean(ReactionTime), 
              CILow = ci.low(ReactionTime), 
              CIHigh = ci.high(ReactionTime)) %>%
    mutate(YMin = MeanReactionTime - CILow, 
           YMax = MeanReactionTime + CIHigh)

agr$Task <- ifelse(agr$Task == "Valence", "Valence", "TruthCond")
agr$Task <- factor(agr$Task, levels = c("TruthCond","Valence"))

# Set dodge width to match violin grouping
dodge_width <- 0.9

ggplot(agr, aes(x = Experiment, y = MeanReactionTime, fill = Task)) + 
  geom_violin(trim = FALSE, alpha = 0.4, position = position_dodge(width = dodge_width)) +

  # Add mean point with matching dodge
  stat_summary(fun = mean,
               geom = "point",
               shape = 23,
               size = 2,
               position = position_dodge(width = dodge_width)) +
  
  stat_summary(fun = median,
                geom = "crossbar",
                width = 0.3, 
                linewidth = 0.2,
                position = position_dodge(width = dodge_width)) +
  
  labs(y = "Mean Reaction Time", x = "Experiment") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10), limits=rev) +
  # scale_x_discrete() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    text = element_text(family = "Helvetica"),
    axis.title.x = element_text(size = 16),     # x-axis title
    axis.text.x  = element_text(size = 12),     # x-axis ticks
    axis.text.y  = element_text(size = 12),     # y-axis ticks
    axis.title.y=element_blank()
  ) +
  coord_flip()

ggsave("../graphs/total_rt_poster.jpg",width = 5, height = 6)
# ggsave("../graphs/exp1_paper.pdf",width = 8, height = 4)
```


