---
title: "Marginal Means Analysis of Truth Conditional Foils"
author: "author"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
library(ggrepel)
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

# v1 <- read_csv("../../01_verbs/exploratory_all_data/data/processed.csv")
# v1["Category"] <- "Verbs"

v <- read_csv("../../01_concreteness/01_verbs/data/processed.csv")
v["Category"] <- "Verbs"
v["Experiment"] <- "Ex1a: Conc-Abs (Verbs)"
v["TruthCond"] <- "Conc-Abs"

n <- read_csv("../../01_concreteness/02_nouns/data/processed.csv")
n["Category"] <- "Nouns"
n["Experiment"] <- "Ex1b: Conc-Abs (Nouns)"
v["TruthCond"] <- "Conc-Abs"

a <- read_csv("../../01_concreteness/03_adjectives/data/processed.csv")
a["Category"] <- "Adjs"
a["Experiment"] <- "Ex1c: Conc-Abs (Adjs)"
a["TruthCond"] <- "Conc-Abs"

a2 <- read_csv("../../03_phys-soc/01_experiment/data/processed.csv")
a2["Category"] <- "Adjs"
a2["Experiment"] <- "Ex2b: Phys-Soc (Adjs)"
a2["TruthCond"] <- "Phys-Soc/Psych"

v2 <- read_csv("../../02_phys-psych/01_experiment/data/processed.csv")
v2["Category"] <- "Verbs"
v2["Experiment"] <- "Ex2a: Phys-Psych (Verbs)"
v2["TruthCond"] <- "Phys-Soc/Psych"


n2 <- read_csv("../../04_animacy/01_experiment/data/processed.csv")
n2["Category"] <- "Nouns"
n2["Experiment"] <- "Ex3: Animacy (Nouns)"
n2["TruthCond"] <- "Animacy"

s <- read_csv("../../05_syntactic/01_experiment/data/processed.csv")
s["Experiment"] <- "Ex4: Syntactic (N v. V)"
s["TruthCond"] <- "Syntactic"


d <- bind_rows(v,n,a,a2,v2,n2,s)

```


# Look at the most accurate for each category on EVERYTHING

```{r}
# Compute highest accuracy for Concrete, keeping top 10 words per Category
concept_acc <- d %>% 
  # filter(Experiment == "Ex1: Conc-Abs") %>% 
  group_by(Experiment,Category, Word, Task) %>%
  mutate(Task = ifelse(Task == "Valence", "Valence", "TruthCond"),
          Task = factor(Task, levels = c("TruthCond","Valence"))) %>% 
  summarize(MeanAccuracy = mean(Accuracy),
            MeanReactionTime = mean(ReactionTime), .groups = "drop") %>% 
  filter(Task == "TruthCond") %>%
  select(Experiment,Category,Word, MeanAccuracy) %>%
  rename(ConcreteAccuracy = MeanAccuracy) %>%
  group_by(Experiment,Category) %>% 
  slice_max(order_by = ConcreteAccuracy, n = 10)  # Get top 10 per category
```

# Reaction Time

## Remove outliers

```{r}
# First remove inaccurate participants
length(unique(d$ID.true))
inacc.parts <- d %>% 
  group_by(Experiment,ID.true,Task,Category) %>% 
  summarise(MeanAccuracy = mean(Accuracy)) %>% 
  filter(MeanAccuracy < .75)
# How many participants have Accuracy < .75?
length(unique(inacc.parts$ID.true))
# Remove them
d.inaccurate.removed <- d %>% 
  anti_join(inacc.parts, by = "ID.true")
# Sanity check
length(unique(d.inaccurate.removed$ID.true))


# Second, remove all inaccurate trials
orig <- nrow(d.inaccurate.removed)
d.inaccurate.removed <- d.inaccurate.removed %>% 
  filter(Accuracy == 1)
nrow(d.inaccurate.removed)/orig*100


# Third, Remove subjects with ReactionTime higher than 3x IQR
summary(d.inaccurate.removed$LogReactionTime)
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 6.924   7.328   7.436   7.479   7.579  10.008 
range(d.inaccurate.removed$LogReactionTime)

hist(d.inaccurate.removed$LogReactionTime, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)
IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 0.7526289
cutoff.high <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[4] + IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 8.419261
cutoff.low <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[2] - IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3# 6.5088838.419261


# remove subjects with ReactionTime higher than 3 x IQR
df.outliers.removed <- subset(d.inaccurate.removed, (d.inaccurate.removed$LogReactionTime > cutoff.low) & (d.inaccurate.removed$LogReactionTime < cutoff.high))

hist(df.outliers.removed$LogReactionTime, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

# write_csv(df.outliers.removed,"../data/categorization.csv")
nrow(df.outliers.removed)

length(unique(d$ID.true)) - length(unique(df.outliers.removed$ID.true))

# What percentage of data lost?
(1 - nrow(df.outliers.removed)/nrow(d)) *100

```

# ARE THERE DIFFERENCES WRT FOIL?

```{r}

df.outliers.removed$TruthCond = as.factor(df.outliers.removed$TruthCond)
df.outliers.removed$TruthCond <- relevel(df.outliers.removed$TruthCond, ref = "Animacy")
df.outliers.removed$Task <- ifelse(df.outliers.removed$Task == "Valence", "Valence", "TruthCond")
df.outliers.removed$Task <- factor(df.outliers.removed$Task, levels = c("TruthCond","Valence"))
write.csv(df.outliers.removed,"../data/cat_task.csv")
```




```{r}

most_acc <- df.outliers.removed %>% 
  filter(Word %in% concept_acc$Word)

most_acc$Task <- ifelse(most_acc$Task == "Valence", "Valence", "TruthCond")
most_acc$Task <- factor(most_acc$Task, levels = c("TruthCond","Valence"))

model <- lmer(LogReactionTime ~ Task * Experiment + 
              (1 | ID.true), data = most_acc)
summary(model)
# Create estimated marginal means
em <- emmeans(model, ~ Task | Experiment)

# Pairwise comparisons
pairs(em)

pairs(em, adjust = "tukey")

```


# ReactionTime by Task




# RT Concept Acc only


## Summary Stats
```{r}
agr <- d.inaccurate.removed %>% 
  filter(Word %in% concept_acc$Word) %>% 
  group_by(Experiment,Task) %>% 
  summarize(MeanRT = mean(ReactionTime),
            SD = sd(ReactionTime),
            MeanLogRT = mean(LogReactionTime))
print(agr)
```


```{r}
# First remove inaccurate participants
length(unique(d$ID.true))
inacc.parts <- d %>% 
  group_by(Experiment,ID.true,Task,Category) %>% 
  summarise(MeanAccuracy = mean(Accuracy)) %>% 
  filter(MeanAccuracy < .75)
# How many participants have Accuracy < .75?
length(unique(inacc.parts$ID.true))
# Remove them
d.inaccurate.removed <- d %>% 
  anti_join(inacc.parts, by = "ID.true") %>% 
  filter(Word %in% concept_acc$Word)
# Sanity check
length(unique(d.inaccurate.removed$ID.true))


# Second, remove all inaccurate trials
orig <- nrow(d.inaccurate.removed)
d.inaccurate.removed <- d.inaccurate.removed %>% 
  filter(Accuracy == 1)
nrow(d.inaccurate.removed)/orig*100


# Third, Remove subjects with ReactionTime higher than 3x IQR
summary(d.inaccurate.removed$LogReactionTime)
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 6.924   7.328   7.436   7.479   7.579  10.008 
range(d.inaccurate.removed$LogReactionTime)

hist(d.inaccurate.removed$LogReactionTime, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)
IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 0.7526289
cutoff.high <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[4] + IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 8.419261
cutoff.low <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[2] - IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3# 6.5088838.419261


# remove subjects with ReactionTime higher than 3 x IQR
df.outliers.removed <- subset(d.inaccurate.removed, (d.inaccurate.removed$LogReactionTime > cutoff.low) & (d.inaccurate.removed$LogReactionTime < cutoff.high))

hist(df.outliers.removed$LogReactionTime, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

```


```{r}

sub <- d.inaccurate.removed


range(sub$ReactionTime[df.outliers.removed$sub == "Ex4: Syntactic"])

# Identify the rows matching the condition
subset_rows <- sub$Experiment == "Ex4: Syntactic"

# Find the index of the maximum ReactionTime within those rows
max_index <- which.max(sub$ReactionTime[subset_rows])

# Get the actual row number in the original dataframe
row_to_remove <- which(subset_rows)[max_index]

# Remove the row
sub <- sub[-row_to_remove, ]

range(sub$LogReactionTime[sub$Experiment == "Ex4: Syntactic"])

ggplot(sub, aes(LogReactionTime, fill=Task)) +
  geom_density(alpha = .5) +
  facet_wrap(~Experiment)

```

```{r}


ggplot(sub, aes(ReactionTime, fill=Task)) +
  geom_density(alpha = .5) +
  facet_wrap(~Experiment)


```



# ReactionTime by Task
```{r}

agr <- df.outliers.removed %>%
  # filter(Word %in% concept_acc$Word) %>% 
    group_by(Experiment,Task,Word,Category) %>%
    summarize(MeanReactionTime = mean(ReactionTime), 
              CILow = ci.low(ReactionTime), 
              CIHigh = ci.high(ReactionTime)) %>%
    mutate(YMin = MeanReactionTime - CILow, 
           YMax = MeanReactionTime + CIHigh)

agr$Task <- ifelse(agr$Task == "Valence", "Valence", "TruthCond")
agr$Task <- factor(agr$Task, levels = c("TruthCond","Valence"))

ggplot(agr, aes(x=Experiment, y=MeanReactionTime,fill=Task)) + 
    geom_violin(trim=FALSE,alpha=.4) +
    geom_jitter(shape=16, position=position_jitter(0.2)) +
    theme(
      legend.position = "top",
      legend.direction = "horizontal",
      legend.title = element_text(size = 10),
      legend.text = element_text(size = 9)
    ) +
  theme(axis.text.x = element_text(angle = 10, hjust = 1))

# ggsave("../graphs/concept_acc_rt.pdf",width = 5, height = 3)
```

## Model
```{r}
dcen <- sub %>% 
  # filter(Word %in% concept_acc$Word) %>% 
  # filter(Experiment == "Ex2: Conc-Abs") %>% 
  mutate(Task = ifelse(Task == "Valence", "Valence", "TruthCond"),
          Task = factor(Task, levels = c("Valence", "TruthCond"))) %>% 
  mutate(Word = as.factor(Word),
         ID.true = as.factor(ID.true),
         Task = as.factor(Task),
         Experiment = as.factor(Experiment),
         cAccuracy = as.numeric(Accuracy)-mean(as.numeric(Accuracy)),
         cTask = as.numeric(Task)-mean(as.numeric(Task)))

m <- lmer(LogReactionTime ~ cTask*Experiment + (1+cTask|Word) + (1+cTask|ID.true), data = dcen)
summary(m)

```





 