---
title: "OS: Reaction Time Graphs"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../../helpers.R")

d <- read.csv("../data/processed.csv")
d$Word <- tolower(d$Word)
d$Word <- as.factor(d$Word)
d$Task <- as.factor(d$Task)
d$ResponseID <- as.factor(d$ResponseID)

# convert to miliseconds
names(d)[names(d) == "ReactionTime"] <- "ReactionTime.s"
d$ReactionTime <- d$ReactionTime.s * 1000
d$LogReactionTime = log(d$ReactionTime)


d <- d %>% 
  filter(!is.na(ReactionTime.s))

```



# Looking at overall Log ReactionTime for the data

Before removing outliers

## Summary Stats
```{r}
agr <- d %>% 
  group_by(Task) %>% 
  summarize(MeanRT = mean(ReactionTime, na.rm = TRUE),
            SD = sd(ReactionTime, na.rm = TRUE),
            MeanLogRT = mean(LogReactionTime, na.rm = TRUE))
print(agr)
```


```{r}

ggplot(d, aes(ReactionTime, fill=Task)) +
  geom_density(alpha = .5)

```

Long tail justifies outlier removal?
```{r}
ggplot(d, aes(LogReactionTime, fill=Task)) +
  geom_density(alpha = .5)

summary(d$LogReactionTime)
```

# First Remove participants who aren't super , aggregating over Task

```{r, eval = FALSE, echo = FALSE}

length(unique(d$ResponseID))
inacc.parts <- d %>% 
  group_by(ResponseID) %>% 
  summarise(MeanAccuracy = mean(Accuracy)) %>% 
  filter(MeanAccuracy < .75)

# How many participants have Accuracy < .75?
length(unique(inacc.parts$ResponseID))

d.inaccurate.removed <- d %>% 
  anti_join(inacc.parts, by = "ResponseID")

# Sanity check
length(unique(d.inaccurate.removed$ResponseID))


# remove all inaccurate trials

orig <- nrow(d.inaccurate.removed)
d.inaccurate.removed <- d.inaccurate.removed %>% 
  filter(Accuracy == 1)
nrow(d.inaccurate.removed)/orig*100


# Remove subjects with ReactionTime higher than 3x IQR
summary(d.inaccurate.removed$LogReactionTime)
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 6.924   7.328   7.436   7.479   7.579  10.008 
range(d.inaccurate.removed$LogReactionTime)

hist(d.inaccurate.removed$LogReactionTime, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)
IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 0.7526289

cutoff.high <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[4] + IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3 # 8.419261
cutoff.low <- quantile(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)[2] - IQR(d.inaccurate.removed$LogReactionTime, na.rm = TRUE)*3# 6.5088838.419261


# remove subjects with ReactionTime higher than 3 x IQR
df.outliers.removed <- subset(d.inaccurate.removed, (d.inaccurate.removed$LogReactionTime > cutoff.low) & (d.inaccurate.removed$LogReactionTime < cutoff.high))

hist(df.outliers.removed$LogReactionTime, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")


```


# LogReactionTime by Task

```{r}

agr <- d %>%
    group_by(Task,Word) %>%
    summarize(MeanLogReactionTime = mean(LogReactionTime), 
              CILow = ci.low(LogReactionTime), 
              CIHigh = ci.high(LogReactionTime)) %>%
    mutate(YMin = MeanLogReactionTime - CILow, 
           YMax = MeanLogReactionTime + CIHigh)

ggplot(agr, aes(x=Task, y=MeanLogReactionTime,fill=Task)) + 
    geom_violin(trim=FALSE,alpha=.4) +
    geom_jitter(shape=16, position=position_jitter(0.2)) +
  guides(fill = "none")

```

# ReactionTime by Task
```{r}

agr <- d %>%
    group_by(Task,Word) %>%
    summarize(MeanReactionTime = mean(ReactionTime), 
              CILow = ci.low(ReactionTime), 
              CIHigh = ci.high(ReactionTime)) %>%
    mutate(YMin = MeanReactionTime - CILow, 
           YMax = MeanReactionTime + CIHigh)

ggplot(agr, aes(x=Task, y=MeanReactionTime,fill=Task)) + 
    geom_violin(trim=FALSE,alpha=.4) +
    geom_jitter(shape=16, position=position_jitter(0.2)) +
  guides(fill = "none")

# ggsave("../graphs/exp1.pdf",width = 3, height = 2)
```


# By Item

```{r,fig.width=10, fig.height=10}
agr <- d %>%
    group_by(Task,Word) %>%
    summarize(MeanReactionTime = mean(ReactionTime), CILow = ci.low(ReactionTime), CIHigh = ci.high(ReactionTime)) %>%
    mutate(YMin = MeanReactionTime - CILow, YMax = MeanReactionTime + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanReactionTime,fill=Task)) +
  geom_bar(position=dodge,stat="identity") +
  facet_wrap(~Word) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```


# convert everything to factors
```{r, include=FALSE, warning=FALSE, echo=FALSE}
str(d)

convert_except <- function(df, exclude_cols) {
  df[] <- lapply(names(df), function(col_name) {
    if (!(col_name %in% exclude_cols)) {
      return(as.factor(df[[col_name]]))  # Convert to factor if not in excluded columns
    } else {
      return(df[[col_name]])  # Leave the excluded columns unchanged
    }
  })
  return(df)
}
# Specify columns to exclude from conversion
exclude_columns <- c('ReactionTime', 'LogReactionTime')

# Convert all columns to factors except for 'a' and 'd'
df_factors <- convert_except(d, exclude_columns)

# Check the structure of the modified data frame
# str(df_factors)

```


```{r, include=FALSE, warning=FALSE, echo=FALSE}
contrasts(df_factors$Task)

center = df_factors %>%
  mutate(cTask = as.numeric(Task)-mean(as.numeric(Task))
         )
  
  # droplevels()
```

# Is there a difference between Semantic and Valence Tasks?
Yes

```{r}

m = lmer(LogReactionTime ~ cTask + (1+cTask|ResponseID) + (1+cTask|Word), data=center)
summary(m)
```
