---
title: "Syntactic: Graphs for Accuracy"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: pdf_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

d <- read.csv("../data/processed.csv")

names(d)

length(unique(d$Word))
print(unique(d$Word))

```


# Graph Accuracy by Word


## Summary Stats
```{r}
agr <- d %>% 
  group_by(Task) %>% 
  summarize(MeanAccuracy = mean(Accuracy),
            SD = sd(Accuracy))
print(agr)
```


## Overall Accuracy

```{r}
agr <- d %>% 
  group_by(Task) %>% 
  reframe(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)
# View(agr)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanAccuracy, fill=Task)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))

```

```{r}
agr <- d %>% 
  group_by(Task,BlockOrder) %>% 
  reframe(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)
# View(agr)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanAccuracy, fill=BlockOrder)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))

```

## Mean Accuracy by Word / Task


```{r,fig.width=10, fig.height=5}
agr <- d %>% 
  group_by(Word,Task,BlockOrder) %>% 
  reframe(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)

ggplot(agr,aes(x=Task, y=MeanAccuracy, alpha=Task, fill=BlockOrder)) +
  geom_bar(position="dodge",stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_wrap(~Word, ncol=10) +
  xlab("Task") +
  ylab("MeanAccuracy") +
  # guides(fill=FALSE) +
  # guides(alpha=guide_legend(title="Task")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    # scale_fill_manual(values=cbPalette) +
    # scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


## Looking at only the first block
```{r,fig.width=10, fig.height=5, eval=FALSE, echo=FALSE}
agr <- d %>%
  group_by(Task,Word,BlockOrder) %>% 
  filter((Task == "Valence") & (BlockOrder == "VS") | 
           (Task == "Syntactic") & (BlockOrder == "SV")) %>% 
  mutate(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)
  
agrr <- agr %>% 
  group_by(Word,Task) %>% 
  select(Word,Task,MeanAccuracy) %>% 
  unique()

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanAccuracy,fill=BlockOrder)) +
  geom_bar(position=dodge,stat="identity") +
  facet_wrap(~Word,ncol=10) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
 
```


# PropPositive and PropConcrete

```{r}
# Extract just "positive" or "negative" from ConcValCombo
valence_part <- regmatches(d$ConcValCombo, regexpr("positive|negative", d$ConcValCombo))

# Create ValSynCombo with extracted valence and Category
d$ValSynCombo <- ifelse(
  !is.na(valence_part),
  paste(valence_part, d$Category, sep = "-"),
  NA
)

```


```{r}
val <- d %>% 
  filter(Task == "Valence") %>% 
  # filter(Word %in% conc$Word) %>% 
  group_by(Word,ValSynCombo) %>%
  mutate(Response.n = as.numeric(factor(Response, levels = c("negative", "positive"))) - 1) %>%  # Convert to numeric and subtract 1
  summarize(PropPositive = mean(Response.n))
  # filter(PropPositive > .1 | PropPositive < .9)

dodge = position_dodge(.9)
ggplot(data=val, aes(x=reorder(Word,PropPositive),y=PropPositive,fill=ValSynCombo)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```


```{r}
conc <- d %>% 
  filter(Task == "Syntactic") %>% 
  # filter(Word %in% conc$Word) %>% 
  group_by(Word,ValSynCombo) %>%
  mutate(Response.n = as.numeric(factor(Response, levels = c("noun", "verb"))) - 1) %>%  # Convert to numeric and subtract 1
  summarize(PropVerb = mean(Response.n))
  # filter(PropPositive > .1 | PropPositive < .9)

dodge = position_dodge(.9)
ggplot(data=conc, aes(x=reorder(Word,PropVerb),y=PropVerb,fill=ValSynCombo)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```


## Accuracy by Participant

```{r,fig.width=10, fig.height=5}
agr <- d %>%
  # filter(PennElementType == "Selector") %>% 
  select(ID.true,Task,Accuracy) %>% 
  group_by(ID.true,Task) %>% 
  mutate(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(ID.true,MeanAccuracy),y=MeanAccuracy,fill=Task)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")

```


# Mean Accuracy by ConcValCombo

```{r}
agr <- d %>%
  group_by(Task,ConcValCombo) %>% 
  summarize(MeanAccuracy = mean(Accuracy), 
            CILow = ci.low(Accuracy), 
            CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanAccuracy,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  # facet_wrap(~Task) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```


# Mean Accuracy by Category

```{r}
agr <- d %>%
  group_by(Task,Category) %>% 
  summarize(MeanAccuracy = mean(Accuracy), 
            CILow = ci.low(Accuracy), 
            CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=Task,y=MeanAccuracy,fill=Category)) +
  geom_bar(position=dodge,stat="identity") +
  # facet_wrap(~Task) +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9))
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")
```


# Remove participants who aren't accurate

```{r}
length(unique(d$ID.true))
inacc.parts <- d %>% 
  group_by(ID.true,Task) %>% 
  summarise(MeanAccuracy = mean(Accuracy)) %>% 
  filter(MeanAccuracy < .75)

# How many participants have Accuracy < .75?
length(unique(inacc.parts$ID.true))

d.inaccurate.removed <- d %>% 
  anti_join(inacc.parts, by = "ID.true")

# Sanity check
length(unique(d.inaccurate.removed$ID.true))

```


## Accuracy by Participant

```{r,fig.width=10, fig.height=5}
agr <- d.inaccurate.removed %>%
  select(ID.true,Task,Accuracy) %>% 
  group_by(ID.true,Task) %>% 
  mutate(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(ID.true,MeanAccuracy),y=MeanAccuracy,fill=Task)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  # guides(fill = "none")

```

## Mean Accuracy by Word / Task
```{r,fig.width=10, fig.height=5}
agr <- d.inaccurate.removed %>%
  group_by(Task,Word,BlockOrder) %>% 
  mutate(MeanAccuracy = mean(Accuracy), 
          CILow = ci.low(Accuracy), 
          CIHigh = ci.high(Accuracy)) %>%
  mutate(YMin = MeanAccuracy - CILow, 
         YMax = MeanAccuracy + CIHigh)
  
ggplot(agr,aes(x=Task, y=MeanAccuracy, alpha=Task, fill=BlockOrder)) +
  geom_bar(position="dodge",stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_wrap(~Word, ncol=10) +
  xlab("Task") +
  ylab("MeanAccuracy") +
  # guides(fill=FALSE) +
  # guides(alpha=guide_legend(title="Task")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    # scale_fill_manual(values=cbPalette) +
    # scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
 
```


