---
title: "Pilot 1: Removing Outliers"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

d <- read.csv("../data/processed.csv")
d$LogRT <- log(d$RT)
```

```{r}
summary(d$LogRT)
```

```{r}

ggplot(d, aes(x=LogRT)) +
  geom_histogram(binwidth = .1,fill = "lightblue", color = "black") +
  facet_wrap(~Task)


```


# First Remove participants who aren't accurate, grouping by Task

```{r}
length(unique(d$ID.true))
inacc.parts <- d %>% 
  group_by(Task,ID.true) %>% 
  summarise(MeanAccuracy = mean(Accuracy)) %>% 
  filter(MeanAccuracy < .75)

# How many participants have accuracy < .75?
length(unique(inacc.parts$ID.true))

d.inaccurate.removed <- d %>% 
  anti_join(inacc.parts, by = "ID.true")

# Sanity check
length(unique(d.inaccurate.removed$ID.true))

```


```{r}
# Remove subjects with ReactionTime higher than 3x IQR
summary(d.inaccurate.removed$LogRT)
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 6.924   7.328   7.436   7.479   7.579  10.008 
range(d.inaccurate.removed$LogRT)

hist(d.inaccurate.removed$LogRT, breaks=100, col="lightblue", xlab="LogReactionTime (ms)",
        main="Histogram with Normal Curve")

quantile(d.inaccurate.removed$LogRT)
IQR(d.inaccurate.removed$LogRT)*3 # 0.7526289
cutoff.high <- quantile(d.inaccurate.removed$LogRT)[4] + IQR(d.inaccurate.removed$LogRT)*3 # 8.419261
cutoff.low <- quantile(d.inaccurate.removed$LogRT)[2] - IQR(d.inaccurate.removed$LogRT)*3# 6.5088838.419261


# remove subjects with ReactionTime higher than 3 x IQR
df.outliers.removed <- subset(d.inaccurate.removed, (d.inaccurate.removed$LogRT > cutoff.low) & (d.inaccurate.removed$LogRT < cutoff.high))

hist(df.outliers.removed$LogRT, col="lightblue", xlab="LogRT (ms)",
        main="Histogram with Normal Curve")


```

```{r, eval=FALSE, echo=FALSE}
# Remove subjects with RT higher than 3x IQR
summary(d$LogRT)
   # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   # 2211    6096    7608    8972    9992  163935 
range(d$LogRT)

hist(d$LogRT, breaks=100, col="red", xlab="LogRT (ms)",
        main="Histogram with Normal Curve")

quantile(d$LogRT)
IQR(d$LogRT)*3 # 0.8187334
cutoff.high <- quantile(d$LogRT)[4] + IQR(d$LogRT)*3 # 8.419261
cutoff.low <- quantile(d$LogRT)[2] - IQR(d$LogRT)*3# 6.5088838.419261


# remove subjects with RT higher than 3 x IQR
df.outliers.removed <- subset(d, (d$LogRT > cutoff.low) & (d$LogRT < cutoff.high))

hist(df.outliers.removed$LogRT, col="red", xlab="LogRT (ms)",
        main="Histogram with Normal Curve")


```

```{r}
df.outliers.removed$Task <- as.factor(df.outliers.removed$Task)
df.outliers.removed$Word <- as.factor(df.outliers.removed$Word)
df.outliers.removed$ID.true <- as.factor(df.outliers.removed$ID.true)
df.outliers.removed$ConcValCombo <- as.factor(df.outliers.removed$ConcValCombo)

center = df.outliers.removed %>%
  mutate(cTask = as.numeric(Task)-mean(as.numeric(Task)),
         cAccuracy = as.numeric(Accuracy)-mean(as.numeric(Accuracy)))
```

# Is there a difference between Semantic and Valence Tasks?
Yes.

```{r}

m = lmer(LogRT ~ cTask + (1|ID.true) + (1+cTask|Word), data=center)
# saveRDS(m.ms.ma.full, "../models/model-task-para.rds")

# m <- readRDS("../models/m.rds")
summary(m)
```

# Is there an Interaction between Task and WordType (ConcValCombo)?
Still no.
```{r}

m = lmer(LogRT ~ cTask*ConcValCombo + (1+ConcValCombo|ID.true) + (1+cTask+ConcValCombo|Word), data=center)
# saveRDS(m.ms.ma.full, "../models/model-task-para.rds")

# m <- readRDS("../models/m.rds")
summary(m)

```

