---
title: 'Pilot 1: Troubleshooting response labels'
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

d <- read.csv("../data/processed.csv")

```

```{r}
table(d.train$Group, d.train$Key_value_F)
table(d.train$Group, d.train$Key_value_J)
```

```{r}
agr <- d %>% 
  filter(Task == "Semantic") %>% 
  filter(Word %in% c("fall","hurl","qualify")) %>% 
  mutate(Response.n = as.numeric(factor(Response, levels = c("abstract", "concrete"))) - 1) %>% 
  group_by(Word,ConcValCombo) %>%
  summarize(PropConcrete = mean(Response.n))
  # select(ID.true, Task,ConcValCombo, Word, WhoseList, Response)

View(agr)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(Word,PropConcrete),y=PropConcrete,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
agr <- d %>% 
  filter(Task == "Semantic") %>% 
  filter(Word %in% c("fall","hurl","qualify")) %>% 
  # mutate(Response.n = as.numeric(factor(Response, levels = c("abstract", "concrete"))) - 1) %>% 
  group_by(Word,ConcValCombo) %>%
  summarize(MeanAccuracy = mean(Accuracy))
  # select(ID.true, Task,ConcValCombo, Word, WhoseList, Response)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(Word,MeanAccuracy),y=MeanAccuracy,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
agr <- d %>% 
  filter(Task == "Semantic") %>% 
  mutate(Response.n = as.numeric(factor(Value, levels = c("abstract", "concrete"))) - 1) %>% 
  group_by(Word,ConcValCombo) %>%
  summarize(PropConcrete = mean(Response.n))
  # select(ID.true, Task,ConcValCombo, Word, WhoseList, Response)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(Word,PropConcrete),y=PropConcrete,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
agr <- d %>% 
  filter(Task == "Valence") %>% 
  mutate(Response.n = as.numeric(factor(Response, levels = c("negative", "positive"))) - 1) %>% 
  group_by(Word,ConcValCombo) %>%
  summarize(PropPositive = mean(Response.n))
  # select(ID.true, Task,ConcValCombo, Word, WhoseList, Response)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(Word,PropPositive),y=PropPositive,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
table(d.train$Group, d.train$Key_value_F)
table(d.train$Group, d.train$Key_value_J)
```


# Concrete and abstact are definitely switched
```{r}
agr <- d %>% 
  filter(Task == "Semantic") %>% 
  mutate(Response.n = as.numeric(factor(Response, levels = c("abstract", "concrete"))) - 1) %>% 
  group_by(ID.true,Word,ConcValCombo) %>%
  summarize(PropConcrete = mean(Response.n))
  # select(ID.true, Task,ConcValCombo, Word, WhoseList, Response)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=ID.true,y=PropConcrete,fill=ConcValCombo)) +
  geom_bar(position=dodge,stat="identity") +
  facet_wrap(~reorder(Word,PropConcrete)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```




```{r}
# Create the ResponseCorrected column
d <- d %>%
  mutate(
    ResponseCorrected = case_when(
      Response == "abstract" ~ "concrete",  # Replace "abstract" with "concrete"
      Response == "concrete" ~ "abstract",  # Replace "concrete" with "abstract"
      TRUE ~ Response  # Keep all other values the same
    ),
    ConcValCorrected = case_when(
      ConcValCombo == "abstract-positive" ~ "concrete-positive",
      ConcValCombo == "concrete-positive" ~ "abstract-positive",
      ConcValCombo == "abstract-negative" ~ "concrete-negative",
      ConcValCombo == "concrete-negative" ~ "abstract-negative",
      TRUE ~ ConcValCombo  # Keep all other values the same
    )
  )




```


```{r}
agr <- d %>% 
  filter(Task == "Semantic") %>% 
  filter(Word %in% c("fall","hurl","qualify")) %>% 
  mutate(ResponseCorrected.n = as.numeric(factor(ResponseCorrected, levels = c("abstract", "concrete"))) - 1) %>%
  group_by(Word,ConcValCorrected) %>%
  summarize(PropConcrete = mean(ResponseCorrected.n))
  # select(ID.true, Task,ConcValCombo, Word, WhoseList, Response)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(Word,PropConcrete),y=PropConcrete,fill=ConcValCorrected)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
agr <- d %>% 
  filter(Task == "Semantic") %>% 
  mutate(ResponseCorrected.n = as.numeric(factor(ResponseCorrected, levels = c("abstract", "concrete"))) - 1) %>% 
  group_by(Word,ConcValCorrected) %>%
  summarize(PropConcrete = mean(ResponseCorrected.n))
  # select(ID.true, Task,ConcValCombo, Word, WhoseList, Response)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(Word,PropConcrete),y=PropConcrete,fill=ConcValCorrected)) +
  geom_bar(position=dodge,stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
# write.csv(d,"../data/p1_corrected.csv")

```

