---
title: 'affect proj pilot: semantic & '
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")
```


```{r}
read.pcibex <- function(filepath, auto.colnames=TRUE, fun.col=function(col,cols){cols[cols==col]<-paste(col,"Ibex",sep=".");return(cols)}) {
  n.cols <- max(count.fields(filepath,sep=",",quote=NULL),na.rm=TRUE)
  if (auto.colnames){
    cols <- c()
    con <- file(filepath, "r")
    while ( TRUE ) {
      line <- readLines(con, n = 1, warn=FALSE)
      if ( length(line) == 0) {
        break
      }
      m <- regmatches(line,regexec("^# (\\d+)\\. (.+)\\.$",line))[[1]]
      if (length(m) == 3) {
        index <- as.numeric(m[2])
        value <- m[3]
        if (is.function(fun.col)){
         cols <- fun.col(value,cols)
        }
        cols[index] <- value
        if (index == n.cols){
          break
        }
      }
    }
    close(con)
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=cols))
  }
  else{
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=seq(1:n.cols)))
  }
}

```


```{r}
# REad in the results

sem <- read.pcibex("../data/results_semantic.csv")
val <- read.pcibex("../data/results_affect.csv")

sem["Task"] <- "semantic"
val["Task"] <- "valence" 
d <- rbind(sem,val)

# sanity check
nrow(sem) + nrow(val) == nrow(d)

d$ID = as.factor(d$ID)
length(unique(d$ID)) # 46

```


# Take a look at comments and Problems
```{r}
unique(d$PennElementType)
comments <- d %>% filter((PennElementType == "TextInput") & (PennElementName == "Comments"))
unique(comments$Value)

comments <- d %>% filter((PennElementType == "TextInput") & (PennElementName == "Problems"))
unique(comments$Value)

comments <- d %>% filter((PennElementType == "TextInput") & (PennElementName == "NativeLang"))
unique(comments$Value)

comments <- d %>% filter((PennElementType == "TextInput") & (PennElementName == "OtherLangs"))

unique(comments$Value)

comments <- d %>% filter((PennElementType == "TextInput") & (PennElementName == "Gender"))
unique(comments$Value)
```



```{r}
# get the IDs in the right way
d.test <- d$Value[(d$PennElementName=="ID") & (d$Parameter == "Final")]


d.IDs <- d %>% select(MD5.hash.of.participant.s.IP.address,ID,Value,Parameter,PennElementName) %>% 
  mutate(ID.true = if_else(PennElementName == "ID" & Parameter == "Final", Value, NA_character_)) %>%  # Value[(PennElementName=="ID") & (Parameter == "Final")])
   select(MD5.hash.of.participant.s.IP.address,ID.true) %>%
   distinct() %>% 
  filter(!is.na(ID.true))

d <- d %>%  merge(., d.IDs, by = c("MD5.hash.of.participant.s.IP.address"))
           

# get the relevant conc and val info for each word
d.labels.test <- read.csv("../data/pilot_val_no_neutral.csv")[,c("Word","ConcValCombo")]


d <- inner_join(d, d.labels.test, by = "Word")

```


# Add a Response column

```{r}
d$Response <- d$Value[d$Parameter=="Selection"]

# words <- d %>% 
#   filter(Parameter=="Selection") %>% 
#   mutate(Response = Value) %>% 
#   select(ID.true,Word,Response)

results <- d %>%
  filter((Label == "test") & (Parameter == "Selection" | Value == "Start")) %>%
  group_by(ID.true,Word) %>%
  summarise( RT = mean(EventTime[Parameter=="Selection"] - EventTime[Value=="Start"]) , N = length(Value)/2 ) 
# %>% 
  # merge(.,words, by = c("ID.true","Word"))

results <- results[,c("ID.true","Word")]

d <- inner_join(d,results, by = c("ID.true","Word") )

```



# Create an Accuracy Column
```{r}
d$Response <- as.character(d$Response)
d$ConcValCombo <- as.character(d$ConcValCombo)
# Create an accuracy column that outputs 1 if participant Response matches our
# normed category in ConcValCombo; 0 otherwise
d$Accuracy <- ifelse(grepl(d$ConcValCombo, d$Response), 1, 0)


# Create the Accuracy column checking if Response is a substring of ConcValCombo
d$Accuracy <- mapply(function(response, pattern) {
  ifelse(grepl(response, pattern), 1, 0)
}, d$Response, d$ConcValCombo)

table(d$ID.true,d$Word)
head(d)

length(unique(d$ID.true))

unique(d$Label)
```

# Add TrialRT
```{r}
d_TaskTime = d %>%
    select(ID.true,Word,ConcValCombo,Task,Response,Accuracy,EventTime,Parameter,Value) %>% 
    group_by(ID.true,Word) %>%
    reframe( RT = mean(EventTime[Parameter=="Selection"] - EventTime[Value=="Start"]))
  # select(-c("N"))

head(d_TaskTime)

nrow(d_TaskTime)

```


```{r}
d_agr <- d %>% 
    filter(Parameter == "Selection") %>%
    select(ID.true,Word,Label,ConcValCombo,Task,Response,Accuracy,EventTime,Value,ReactionTime) %>% 
  distinct()


d_total <-  merge(d_agr, d_TaskTime, by = c("ID.true","Word"))

nrow(d_total)

table(d_total$Response)


# write.csv(d_total,"../data/processed.csv")

```

# Compare the RT and ReactionTime columns
```{r}
d_total$ReactionTime <- as.numeric(d_total$ReactionTime)
d_total$LogReactionTime <- log(d_total$ReactionTime)
d_total$RT <- as.numeric(d_total$RT)
d_total$LogRT <- log(d_total$RT)

agr.rt1 = d_total %>%
    group_by(Task,Word) %>%
    summarize(MeanLogReactionTime = mean(LogReactionTime), 
              CILow = ci.low(LogReactionTime), 
              CIHigh = ci.high(LogReactionTime)) %>%
    mutate(YMin = MeanLogReactionTime - CILow, 
           YMax = MeanLogReactionTime + CIHigh)

agr.rt2 = d_total %>%
    group_by(Task,Word) %>%
    summarize(MeanLogRT = mean(LogRT), 
              CILow = ci.low(LogRT), 
              CIHigh = ci.high(LogRT)) %>%
    mutate(YMin = MeanLogRT - CILow, 
           YMax = MeanLogRT + CIHigh)

```

```{r}


ggplot(agr.rt1, aes(x=MeanLogReactionTime, fill=Task)) +
  geom_density(alpha = .4)

ggplot(agr.rt2, aes(x=MeanLogRT, fill=Task)) +
  geom_density(alpha = .4)
```


```{r}

ggplot(agr.rt1, aes(x=Task, y=MeanLogReactionTime,fill=Task)) + 
    geom_violin(trim=FALSE,alpha=.4) +
    geom_jitter(shape=16, position=position_jitter(0.2)) +
    # geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position="dodge", show.legend = FALSE) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = "none")


ggplot(agr.rt2, aes(x=Task, y=MeanLogRT,fill=Task)) + 
    geom_violin(trim=FALSE,alpha=.4) +
    geom_jitter(shape=16, position=position_jitter(0.2)) +
    # geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position="dodge", show.legend = FALSE) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = "none")
```




